In [1]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

cid ="" 
secret = ""

client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

In [2]:
artist_name = []
track_name = []
popularity = []
track_id = []

for i in range(0,10000,50):
    track_results = sp.search(q='year:2015', type='track', limit=50,offset=i)
    for i, t in enumerate(track_results['tracks']['items']):
        artist_name.append(t['artists'][0]['name'])
        track_name.append(t['name'])
        track_id.append(t['id'])
        popularity.append(t['popularity'])

import pandas as pd

df_tracks = pd.DataFrame({'artist_name':artist_name,'track_name':track_name,'track_id':track_id,'popularity':popularity})
print(df_tracks.shape)
df_tracks.head()

(10000, 4)

,artist_name,track_name,track_id,popularity
0,Tame Impala,The Less I Know The Better,6K4t31amVTZDgR3sKmwUJJ,86
1,Bryson Tiller,Don't,3pXF1nA74528Edde4of9CC,81
2,Bryson Tiller,Exchange,43PuMrRfbyyuz4QpZ3oAwN,80
3,Chris Stapleton,Tennessee Whiskey,3fqwjXwUGN6vbzIwvyFMhx,78
4,White Noise Meditation,Brown Noise - Loopable with No Fade,67iF3DdebmElASIGoebYt1,77

In [4]:
df_tracks.to_csv(r'songs2015.csv')

In [5]:
artist_name = []
track_name = []
popularity = []
track_id = []

for i in range(0,10000,50):
    track_results = sp.search(q='year:2016', type='track', limit=50,offset=i)
    for i, t in enumerate(track_results['tracks']['items']):
        artist_name.append(t['artists'][0]['name'])
        track_name.append(t['name'])
        track_id.append(t['id'])
        popularity.append(t['popularity'])

import pandas as pd

df_tracks = pd.DataFrame({'artist_name':artist_name,'track_name':track_name,'track_id':track_id,'popularity':popularity})
print(df_tracks.shape)
df_tracks.head()

(10000, 4)

    artist_name            track_name                track_id  popularity
0         Lizzo          Good As Hell  3Yh9lZcWyKrK9GjbhuS0hR          89
1   Post Malone          I Fall Apart  75ZvA4QfFiZvzhj2xkaWAh          85
2  Travis Scott            goosebumps  6gBFPUFcJLzWGx4lenP6h2          88
3   Post Malone       Congratulations  3a1lNhkSLSkpJE4MSHpDu9          85
4  James Arthur  Say You Won't Let Go  5uCax9HTNlzGybIStD3vDh          86

In [6]:
df_tracks.to_csv(r'songs2016.csv')

In [7]:
artist_name = []
track_name = []
popularity = []
track_id = []

for i in range(0,10000,50):
    track_results = sp.search(q='year:2017', type='track', limit=50,offset=i)
    for i, t in enumerate(track_results['tracks']['items']):
        artist_name.append(t['artists'][0]['name'])
        track_name.append(t['name'])
        track_id.append(t['id'])
        popularity.append(t['popularity'])

import pandas as pd

df_tracks = pd.DataFrame({'artist_name':artist_name,'track_name':track_name,'track_id':track_id,'popularity':popularity})
print(df_tracks.shape)
df_tracks.head()

(10000, 4)

,artist_name,track_name,track_id,popularity
0,XXXTENTACION,Jocelyn Flores,7m9OqQk4RVRkw9JJdeAw96,87
1,Granular,White Noise - 500 hz,65rkHetZXO6DQmBh3C2YtW,84
2,XXXTENTACION,Fuck Love (feat. Trippie Redd),7AQim7LbvFVZJE3O8TYgf2,85
3,Lil Uzi Vert,XO Tour Llif3,7GX5flRQZVHRAGd6B4TmDO,85
4,Offset,Ric Flair Drip (& Metro Boomin),7sO5G9EABYOXQKNPNiE9NR,83

In [8]:
df_tracks.to_csv(r'songs2017.csv')

In [9]:
artist_name = []
track_name = []
popularity = []
track_id = []

for i in range(0,10000,50):
    track_results = sp.search(q='year:2018', type='track', limit=50,offset=i)
    for i, t in enumerate(track_results['tracks']['items']):
        artist_name.append(t['artists'][0]['name'])
        track_name.append(t['name'])
        track_id.append(t['id'])
        popularity.append(t['popularity'])

import pandas as pd

df_tracks = pd.DataFrame({'artist_name':artist_name,'track_name':track_name,'track_id':track_id,'popularity':popularity})
print(df_tracks.shape)
df_tracks.head()

(10000, 4)

,artist_name,track_name,track_id,popularity
0,Post Malone,Sunflower - Spider-Man: Into the Spider-Verse,3KkXRkHbMCARz0aVfEt68P,90
1,Travis Scott,SICKO MODE,2xLMifQCjDGFmkHkpNLD9h,89
2,Lil Baby,Drip Too Hard (Lil Baby & Gunna),78QR3Wp35dqAhFEc2qAGjE,86
3,Juice WRLD,Lucid Dreams,285pBltuF7vW8TeWk8hdRR,88
4,YNW Melly,Murder On My Mind,7eBqSVxrzQZtK2mmgRG6lC,86

In [10]:
df_tracks.to_csv(r'songs2018.csv')

In [11]:
artist_name = []
track_name = []
popularity = []
track_id = []

for i in range(0,10000,50):
    track_results = sp.search(q='year:2019', type='track', limit=50,offset=i)
    for i, t in enumerate(track_results['tracks']['items']):
        artist_name.append(t['artists'][0]['name'])
        track_name.append(t['name'])
        track_id.append(t['id'])
        popularity.append(t['popularity'])

import pandas as pd

df_tracks = pd.DataFrame({'artist_name':artist_name,'track_name':track_name,'track_id':track_id,'popularity':popularity})
print(df_tracks.shape)
df_tracks.head()

(10000, 4)

,artist_name,track_name,track_id,popularity
0,Travis Scott,HIGHEST IN THE ROOM,3eekarcy7kvN4yt5ZFzltW,99
1,Post Malone,Circles,21jGcNKet2qwijlDFuPiPb,100
2,Juice WRLD,Bandit (with YoungBoy Never Broke Again),6Gg1gjgKi2AK4e0qzsR7sd,94
3,Selena Gomez,Lose You To Love Me,1HfMVBKM75vxSfsQ5VefZ5,98
4,YNW Melly,223's (feat. 9lokknine),4sjiIpEv617LDXaidKioOI,92

In [12]:
df_tracks.to_csv(r'songs2019.csv')

In [15]:
df15 = pd.read_csv('songs2015.csv')
df16 = pd.read_csv('songs2016.csv')
df17 = pd.read_csv('songs2017.csv')
df18 = pd.read_csv('songs2018.csv')
df19 = pd.read_csv('songs2019.csv')

        Unnamed: 0    popularity
count  10000.00000  10000.000000
mean    4999.50000     49.632300
std     2886.89568      8.070242
min        0.00000     36.000000
25%     2499.75000     43.000000
50%     4999.50000     48.000000
75%     7499.25000     54.000000
max     9999.00000     86.000000

In [33]:
track_results['tracks']['items'][0]

{'album': {'album_type': 'single',
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7ladzyDVpwhv848vat5v9P'},
    'href': 'https://api.spotify.com/v1/artists/7ladzyDVpwhv848vat5v9P',
    'id': '7ladzyDVpwhv848vat5v9P',
    'name': 'Mr. Tape',
    'type': 'artist',
    'uri': 'spotify:artist:7ladzyDVpwhv848vat5v9P'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/6TQj5BFPooTa08A7pk8AQ1'},
    'href': 'https://api.spotify.com/v1/artists/6TQj5BFPooTa08A7pk8AQ1',
    'id': '6TQj5BFPooTa08A7pk8AQ1',
    'name': 'Kaskade',
    'type': 'artist',
    'uri': 'spotify:artist:6TQj5BFPooTa08A7pk8AQ1'}],
  'available_markets': ['AD',
   'AE',
   'AR',
   'AT',
   'AU',
   'BE',
   'BG',
   'BH',
   'BO',
   'BR',
   'CA',
   'CH',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DE',
   'DK',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'FI',
   'FR',
   'GB',
   'GR',
   'GT',
   'HK',
   'HN',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IS',
   'IT',
   'JO',
   'JP',
   'KW',
   'LB',
   'LI',
   'LT',
   'LU',
   'LV',
   'MA',
   'MC',
   'MT',
   'MX',
   'MY',
   'NI',
   'NL',
   'NO',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PH',
   'PL',
   'PS',
   'PT',
   'PY',
   'QA',
   'RO',
   'SA',
   'SE',
   'SG',
   'SK',
   'SV',
   'TH',
   'TN',
   'TR',
   'TW',
   'US',
   'UY',
   'VN',
   'ZA'],
  'external_urls': {'spotify': 'https://open.spotify.com/album/5U5lS9AtiIvsy5Bc58mU38'},
  'href': 'https://api.spotify.com/v1/albums/5U5lS9AtiIvsy5Bc58mU38',
  'id': '5U5lS9AtiIvsy5Bc58mU38',
  'images': [{'height': 640,
    'url': 'https://i.scdn.co/image/edc62ff4a22a0d806916e96e4460a08bb7cbb1d3',
    'width': 640},
   {'height': 300,
    'url': 'https://i.scdn.co/image/144a580c8f2f527be4b968a6c724f8b514f49e0a',
    'width': 300},
   {'height': 64,
    'url': 'https://i.scdn.co/image/7a1b9e26d53b81f5f98ab5f80555425aba5c7f00',
    'width': 64}],
  'name': 'Come On',
  'release_date': '2019-10-25',
  'release_date_precision': 'day',
  'total_tracks': 1,
  'type': 'album',
  'uri': 'spotify:album:5U5lS9AtiIvsy5Bc58mU38'},
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7ladzyDVpwhv848vat5v9P'},
   'href': 'https://api.spotify.com/v1/artists/7ladzyDVpwhv848vat5v9P',
   'id': '7ladzyDVpwhv848vat5v9P',
   'name': 'Mr. Tape',
   'type': 'artist',
   'uri': 'spotify:artist:7ladzyDVpwhv848vat5v9P'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/6TQj5BFPooTa08A7pk8AQ1'},
   'href': 'https://api.spotify.com/v1/artists/6TQj5BFPooTa08A7pk8AQ1',
   'id': '6TQj5BFPooTa08A7pk8AQ1',
   'name': 'Kaskade',
   'type': 'artist',
   'uri': 'spotify:artist:6TQj5BFPooTa08A7pk8AQ1'}],
 'available_markets': ['AD',
  'AE',
  'AR',
  'AT',
  'AU',
  'BE',
  'BG',
  'BH',
  'BO',
  'BR',
  'CA',
  'CH',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DE',
  'DK',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'ES',
  'FI',
  'FR',
  'GB',
  'GR',
  'GT',
  'HK',
  'HN',
  'HU',
  'ID',
  'IE',
  'IL',
  'IN',
  'IS',
  'IT',
  'JO',
  'JP',
  'KW',
  'LB',
  'LI',
  'LT',
  'LU',
  'LV',
  'MA',
  'MC',
  'MT',
  'MX',
  'MY',
  'NI',
  'NL',
  'NO',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PH',
  'PL',
  'PS',
  'PT',
  'PY',
  'QA',
  'RO',
  'SA',
  'SE',
  'SG',
  'SK',
  'SV',
  'TH',
  'TN',
  'TR',
  'TW',
  'US',
  'UY',
  'VN',
  'ZA'],
 'disc_number': 1,
 'duration_ms': 235075,
 'explicit': False,
 'external_ids': {'isrc': 'GBKPL1968479'},
 'external_urls': {'spotify': 'https://open.spotify.com/track/2bKY1VyV0gQ5hXy6dEX79R'},
 'href': 'https://api.spotify.com/v1/tracks/2bKY1VyV0gQ5hXy6dEX79R',
 'id': '2bKY1VyV0gQ5hXy6dEX79R',
 'is_local': False,
 'name': 'Come On',
 'popularity': 55,
 'preview_url': 'https://p.scdn.co/mp3-preview/e315f77b3c2313fcfb27ef7ef5ae5bc7f5bf319e?cid=3258e3ed80d648b1a7da290a44331c42',
 'track_number': 1,
 'type': 'track',
 'uri': 'spotify:track:2bKY1VyV0gQ5hXy6dEX79R'}